src/Entity/ConnectionHistory.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ConnectionHistoryRepository")
 */
class ConnectionHistory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ip;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="connectionHistories", cascade={"remove"})
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_login;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $host_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->last_login = new DateTime('now');
        $this->ip = $_SERVER['REMOTE_ADDR'];
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLastLogin(): ?DateTimeInterface
    {
        return $this->last_login;
    }

    public function setLastLogin(DateTimeInterface $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }

    public function getHostName(): ?string
    {
        return $this->host_name;
    }

    public function setHostName(string $host_name): self
    {
        $this->host_name = $host_name;

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @UniqueEntity(fields={"siret"}, message="Le numéro de SIRET est déjà utilisé.")
 * @UniqueEntity(fields={"name"}, message="Le nom de l'entreprise est déjà utilisé.")
 * @UniqueEntity(fields={"email1"}, message="L'adresse email est déjà utilisé.")
 * @UniqueEntity(fields={"email2"}, message="L'adresse email est déjà utilisé.")
 * @UniqueEntity(fields={"tel1"}, message="Le numéro de téléphone est déjà utilisé.")
 * @UniqueEntity(fields={"tel2"}, message="Le numéro de téléphone est déjà utilisé.")
 * @ORM\Table(name="page", indexes={@ORM\Index(columns={"name"}, flags={"fulltext"})})
 */
class Page implements Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=90)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=14, nullable=false)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NafCode")
     * @ORM\JoinColumn(nullable=false)
     */
    private $naf_code;

    /**
     * @ORM\Column(type="string", length=10, nullable=false)
     */
    private $tel1;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $tel2;

    /**
     * @ORM\Column(type="string", length=80, nullable=false)
     */
    private $email1;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $email2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $valide_admin;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="id_user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_activaded;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $address_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $tel1_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $siret_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $email1_published;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $fax;

    /**
     * @ORM\OneToOne(targetEntity=ImageLogo::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $imageLogo;

    /**
     * @ORM\OneToOne(targetEntity=ImageBan::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $imageBan;

    /**
     * @ORM\OneToOne(targetEntity=Schedule::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $schedule;

    /**
     * @ORM\Column(type="boolean")
     */
    private $schedule_published;

    /**
     * @ORM\OneToOne(targetEntity=Social::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $social;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="page")
     */
    private $services;

    /**
     * @ORM\OneToMany(targetEntity=ContactPro::class, mappedBy="page")
     */
    private $contacts;
    private $id_user;

    /**
     * Page constructor.
     */
    public function __construct()
    {
        $this->created_at = new DateTime('now');
        $this->valide_admin = 0;
        $this->is_published = 0;
        $this->is_activaded = 0;
        $this->schedule_published = 0;
        $this->services = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIdUser(): ?Page
    {
        return $this->id_user;
    }

    public function setIdUser(City $id_user): self
    {
        $this->id_user = $id_user;

        // set the owning side of the relation if necessary
        if ($id_user->getUser() !== $this) {
            $id_user->setUser($this);
        }

        return $this;
    }

    public function getTel1(): ?string
    {
        return $this->tel1;
    }

    public function setTel1(?string $tel1): self
    {
        $this->tel1 = $tel1;

        return $this;
    }

    public function getTel2(): ?string
    {
        return $this->tel2;
    }

    public function setTel2(?string $tel2): self
    {
        $this->tel2 = $tel2;

        return $this;
    }

    public function getEmail1(): ?string
    {
        return $this->email1;
    }

    public function setEmail1(?string $email1): self
    {
        $this->email1 = $email1;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email2;
    }

    public function setEmail2(?string $email2): self
    {
        $this->email2 = $email2;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getValideAdmin(): ?bool
    {
        return $this->valide_admin;
    }

    public function setValideAdmin(bool $valide_admin): self
    {
        $this->valide_admin = $valide_admin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getNafCode(): ?NafCode
    {
        return $this->naf_code;
    }

    public function setNafCode(?NafCode $naf_code): self
    {
        $this->naf_code = $naf_code;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getIsActivaded(): ?bool
    {
        return $this->is_activaded;
    }

    public function setIsActivaded(bool $is_activaded): self
    {
        $this->is_activaded = $is_activaded;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getAddressPublished(): ?bool
    {
        return $this->address_published;
    }

    public function setAddressPublished(bool $address_published): self
    {
        $this->address_published = $address_published;

        return $this;
    }

    public function getTel1Published(): ?bool
    {
        return $this->tel1_published;
    }

    public function setTel1Published(bool $tel1_published): self
    {
        $this->tel1_published = $tel1_published;

        return $this;
    }

    public function getSiretPublished(): ?bool
    {
        return $this->siret_published;
    }

    public function setSiretPublished(bool $siret_published): self
    {
        $this->siret_published = $siret_published;

        return $this;
    }


    public function getSchedulePublished(): ?bool
    {
        return $this->schedule_published;
    }

    public function setSchedulePublished(bool $schedule_published): self
    {
        $this->schedule_published = $schedule_published;

        return $this;
    }


    public function getEmail1Published(): ?bool
    {
        return $this->email1_published;
    }

    public function setEmail1Published(bool $email1_published): self
    {
        $this->email1_published = $email1_published;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getImageLogo(): ?ImageLogo
    {

src/Controller/Profile/ConnectionHistoryController.php
<?php

namespace App\Controller\Profile;

use App\Exception\RedirectException;
use App\Service\PageProService;
use App\Service\ProfileService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ConnectionHistoryController
 * @package App\Controller\Profile
 * @Route("/profil")
 */
class ConnectionHistoryController extends AbstractController
{
    /**
     * @Route("/{id}/historique-connexion", name="connection_history", schemes={"https"}, requirements={"id"="\d+"})
     * @param Request $request
     * @param $id
     * @param ProfileService $profileService
     * @param PageProService $pageProService
     * @return RedirectResponse|Response
     * @throws RedirectException
     */
    public function index(
        Request $request,
        $id,
        ProfileService $profileService,
        PageProService $pageProService
    ) {
        $profileService->checkGetIdUser($profileService->getIdUser(), $request->get('id'));

        $connection_history = $profileService->connectionHistory($id);

        $check = $pageProService->PagePro($id);

        return $this->render('profile/connection_history.html.twig', [
            'connection_history' => $connection_history,
            'check' => $check
        ]);
    }
}

src/Controller/Profile/EditPasswordController.php
<?php

namespace App\Controller\Profile;

use App\Service\PageProService;
use App\Service\ProfileService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * Class EditPasswordController
 * @package App\Controller\Profile
 * @Route("/profil")
 */
class EditPasswordController extends AbstractController
{
    /**
     * @Route("/{id}/edit-mot-de-passe/{token}", name="edit_password", schemes={"https"}, requirements={"id"="\d+"})
     * @param Request $request
     * @param $id
     * @param TokenStorageInterface $tokenStorage
     * @param ProfileService $profileService
     * @param PageProService $pageProService
     * @return RedirectResponse|Response
     */
    public function index(
        Request $request,
        $id,
        TokenStorageInterface $tokenStorage,
        ProfileService $profileService,
        PageProService $pageProService
    ) {
        $profileService->checkGetIdUser($profileService->getIdUser(), $request->get('id'));


        $formPassword = $profileService->editPassword($request, $id);

        if ($formPassword->isSubmitted() && $formPassword->isValid()) {
            $this->addFlash('success', 'Mot de passe modifié');
            return $this->redirectToRoute('profile', ['id' => $id]);
        }

        $check = $pageProService->PagePro($id);

        /**
         * Check Token Edit
         */
        $submittedToken = $request->get('token');
        if (!$this->isCsrfTokenValid('edit_password', $submittedToken)) {
            return $this->redirectToRoute('home');
        }

        return $this->render('profile/edit_password.html.twig', [
            'formPassword' => $formPassword->createView(),
            'check' => $check
        ]);
    }
}

src/Controller/Profile/EditProfileController.php
<?php

namespace App\Controller\Profile;

use App\Exception\RedirectException;
use App\Service\PageProService;
use App\Service\ProfileService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class EditProfileController
 * @package App\Controller\Profile
 * @Route("/profil")
 */
class EditProfileController extends AbstractController
{

    /**
     * @Route("/{id}/edit/{token}", name="profile_edit", schemes={"https"}, requirements={"id"="\d+"})
     * @param Request $request
     * @param $id
     * @param ProfileService $profileService
     * @param PageProService $pageProService
     * @return RedirectResponse|Response
     * @throws RedirectException
     */
    public function index(
        Request $request,
        $id,
        ProfileService $profileService,
        PageProService $pageProService
    ) {
        $profileService->checkGetIdUser($profileService->getIdUser(), $request->get('id'));


        $formEdit = $profileService->editProfileUser($request);

        if ($formEdit->isSubmitted() && $formEdit->isValid()) {
            $this->addFlash('success', 'Votre profil à bien été modifié');
            return $this->redirectToRoute('profile', ['id' => $id]);
        }

        /**
         * Check Token Edit
         */
        $submittedToken = $request->get('token');
        if (!$this->isCsrfTokenValid('profile_edit', $submittedToken)) {
            return $this->redirectToRoute('home');
        }

        $check = $pageProService->PagePro($id);

        return $this->render('profile/edit_profile.html.twig', [
            'form' => $formEdit->createView(),
            'check' => $check
        ]);
    }
}

templates/profile/connection_history.html.twig
{% extends "base.html.twig" %}

{% block title %}Historique de connexion | {{ parent()}} {% endblock %}

{% block body %}

    <section id="content">

        {% include "profile/menu.html.twig" %}

        <div class="container clearfix">

            <div class="content-wrap">

                <div class="row">

                    <div class="col-lg-8 offset-lg-2">
                        <h2>
                            Historique de connexion
                        </h2>

                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>IP</th>
                                <th>Nom de l'hôte</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for history in connection_history %}
                                <tr>
                                    <td>
                                        <code>{{ history.lastLogin|date('d/m/Y à H:i:s') }}</code>
                                    </td>
                                    <td>{{ history.ip }}</td>
                                    <td>{{ history.hostName }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>

                    </div>

                </div>

            </div>

        </div>

    </section>

{% endblock %}

templates/profile/connection_history_pro.html.twig
{% extends 'pagepro/base.html.twig' %}

{% block title %}Edition vos horaires | {{ parent()}} {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/vendors/data-tables/css/jquery.dataTables.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/vendors/data-tables/css/select.dataTables.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/css/pages/data-tables.css') }}">
{% endblock %}
{% block body %}
    <div class="row">
        <div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
        <div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
            <!-- Search for small screen-->
            <div class="container">
                <div class="row">
                    <div class="col s10 m6 l6">
                        <h5 class="breadcrumbs-title mt-0 mb-0"><span>Historique de connexion</span></h5>
                    </div>
                </div>
            </div>
        </div>
        <section class="tabs-vertical mt-1 section">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">
                            <div class="row">
                                <div class="col s12">
                                    <table id="page-length-option" class="display">
                                        <thead>
                                        <tr>
                                            <th>Dernière connexion</th>
                                            <th>Nom de l'hôte</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for history in connection_history %}
                                            <tr>
                                                <td>{{ history.lastLogin|date('d/m/Y à H:i:s') }}</td>
                                                <td>{{ history.hostName }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>Dernière connexion</th>
                                            <th>Nom de l'hôte</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

 {% block javascripts %}
     <script src="{{ asset('pagepro/vendors/data-tables/js/jquery.dataTables.min.js') }}"></script>
     <script src="{{ asset('pagepro/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js') }}"></script>
     <script src="{{ asset('pagepro/vendors/data-tables/js/dataTables.select.min.js') }}"></script>
     <script src="{{ asset('pagepro/js/scripts/data-tables.js') }}"></script>
 {% endblock %}

templates/profile/message.html.twig
{% extends 'pagepro/base.html.twig' %}
{% block title %}Message : {{ message.subject}} | {{ parent()}} {% endblock %}
{% block stylesheets %}
 <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/vendors/quill/quill.snow.css') }}">
 <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/css/pages/app-sidebar.css') }}">
 <link rel="stylesheet" type="text/css" href="{{ asset('pagepro/css/pages/app-email-content.css') }}">
{% endblock %}
{% block body %}

 <div class="row">
  <div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
  <div class="col s12">
   <div class="container">
    <!-- Sidebar Area Starts -->
    <div class="sidebar-left sidebar-fixed">
     <div class="sidebar">
      <div class="sidebar-content">
       <div class="sidebar-header">
        <div class="sidebar-details">
         <h5 class="m-0 sidebar-title"><i class="material-icons app-header-icon text-top">mail_outline</i> Mailbox</h5>
         <div class="row valign-wrapper mt-10 pt-2">
          <div class="col s3 media-image">
           <img src="{{ asset('pagepro/images/avatar/avatar-3.png') }}" alt="" class="circle z-depth-2 responsive-img">
           <!-- notice the "circle" class -->
          </div>
          <div class="col s9">
           <p class="m-0 subtitle font-weight-700">Lawrence Collins</p>
           <p class="m-0 text-muted">lawrence.collins@xyz.com</p>
          </div>
         </div>
        </div>
       </div>
       <div id="sidebar-list" class="sidebar-menu list-group position-relative">
        <div class="sidebar-list-padding app-sidebar sidenav" id="email-sidenav">
         <ul class="email-list display-grid">
          <li class="sidebar-title">Folders</li>
          <li class="active"><a href="#" class="text-sub"><i class="material-icons mr-2"> mail_outline </i> Inbox</a>
          </li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> send </i> Sent</a></li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> description </i> Draft</a></li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> info_outline </i> Span</a></li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> delete </i> Trash</a></li>
          <li class="sidebar-title">Filters</li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> star_border </i> Starred</a></li>
          <li><a href="#" class="text-sub"><i class="material-icons mr-2"> label_outline </i> Important</a></li>
          <li class="sidebar-title">Labels</li>
          <li><a href="#" class="text-sub"><i class="purple-text material-icons small-icons mr-2">
             fiber_manual_record </i> Note</a></li>
          <li><a href="#" class="text-sub"><i class="amber-text material-icons small-icons mr-2">
             fiber_manual_record </i> Paypal</a></li>
          <li><a href="#" class="text-sub"><i class="light-green-text material-icons small-icons mr-2">
             fiber_manual_record </i> Invoice</a></li>
         </ul>
        </div>
       </div>
       <a href="#" data-target="email-sidenav" class="sidenav-trigger hide-on-large-only"><i
                class="material-icons">menu</i></a>
      </div>
     </div>
    </div>
    <!-- Sidebar Area Ends -->
    <!-- Content Area Starts -->
    <div class="app-email-content">
     <div class="content-area content-right">
      <div class="app-wrapper">
       <div class="card card-default scrollspy border-radius-6 fixed-width">
        <div class="card-content pt-0">
         <div class="row">
          <div class="col s12">
           <!-- Email Header -->
           <div class="email-header">
            <div class="subject">
             <div class="back-to-mails">
              <a href="{{ path('list_message', {'id': app.user.id, 'token': csrf_token('list_message') } ) }}"><i class="material-icons">arrow_back</i></a>
             </div>
             <div class="email-title">{{ message.subject }}</div>
            </div>
            <div class="header-action">
                  <span class="badge grey lighten-2"><i class="amber-text material-icons small-icons mr-2">
                      fiber_manual_record </i>Paypal</span>
             <div class="favorite">
              <i class="material-icons">star_border</i>
             </div>
             <div class="email-label">
              <i class="material-icons">label_outline</i>
             </div>
            </div>
           </div>
           <!-- Email Header Ends -->
           <hr>
           <!-- Email Content -->
           <div class="email-content">
            <div class="list-title-area">
             <div class="user-media">
              <img src="{{ asset('pagepro/images/avatar/avatar-3.png') }}" alt=""
                   class="circle z-depth-2 responsive-img avtar">
              <div class="list-title">
               <span class="name">{{ message.user.firstName|capitalize }} {{ message.user.lastName|capitalize }}</span>
              </div>
             </div>
             <div class="title-right">
              <span class="mail-time">{{ message.createdAt|date('d M Y à H:i') }}</span>
              <i class="material-icons">reply</i>
              <i class="material-icons">more_vert</i>
             </div>
            </div>
            <div class="email-desc">
             {{ message.message|raw }}
            </div>
           </div>
           <!-- Email Content Ends -->
           <hr>
           <!-- Email Footer -->
           <div class="email-footer">
            <h6 class="footer-title"> (3)</h6>
            <div class="footer-action">
             <div class="footer-buttons">
              <a class="btn reply mb-1"><i class="material-icons left">reply</i><span>Répondre</span></a>
              <a class="btn red mb-1"><i class="material-icons left">warning</i><span>Signaler</span></a>
             </div>
            </div>
            <div class="reply-box d-none">
             <form action="#">
              <div class="input-field col s12">
               <div class="snow-container mt-2">
                <div class="compose-editor"></div>
                <div class="compose-quill-toolbar">
                          <span class="ql-formats mr-0">
                            <button class="ql-bold"></button>
                            <button class="ql-italic"></button>
                            <button class="ql-underline"></button>
                            <button class="ql-link"></button>
                            <button class="ql-image"></button>
                          </span>
                </div>
               </div>
              </div>
              <div class="input-field col s12">
               <a class="btn reply-btn right">Envoyer</a>
              </div>
             </form>
            </div>
            <div class="forward-box d-none">
             <hr>
             <form action="#">
              <div class="input-field col s12">
               <i class="material-icons prefix"> person_outline </i>
               <input id="email" type="email" class="validate">
               <label for="email">To</label>
              </div>
              <div class="input-field col s12">
               <i class="material-icons prefix"> title </i>
               <input id="subject" type="text" class="validate">
               <label for="subject">Subject</label>
              </div>
              <div class="input-field col s12">
               <div class="snow-container mt-2">
                <div class="forward-email"></div>
                <div class="forward-email-toolbar">
                          <span class="ql-formats mr-0">
                            <button class="ql-bold"></button>
                            <button class="ql-italic"></button>
                            <button class="ql-underline"></button>
                            <button class="ql-link"></button>
                            <button class="ql-image"></button>
                          </span>
                </div>
               </div>
              </div>
              <div class="input-field col s12">
               <a class="btn forward-btn right">Forward</a>
              </div>
             </form>
            </div>
           </div>
           <!-- Email Footer Ends -->
          </div>
         </div>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="content-overlay"></div>
  </div>
 </div>

{% endblock %}

 {% block javascripts %}
  <script src="{{ asset('pagepro/vendors/quill/quill.min.js') }}"></script>
  <script src="{{ asset('pagepro/js/scripts/app-email-content.js') }}"></script>
 {% endblock %}