src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Page::class, inversedBy="services")
     */
    private $page;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imgService;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $content_back;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color_back;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tag;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPage(): ?Page
    {
        return $this->page;
    }

    public function setPage(?Page $page): self
    {
        $this->page = $page;

        return $this;
    }

    public function getImgService(): ?string
    {
        return $this->imgService;
    }

    public function setImgService(string $imgService): self
    {
        $this->imgService = $imgService;

        return $this;
    }

    public function getContentBack(): ?string
    {
        return $this->content_back;
    }

    public function setContentBack(?string $content_back): self
    {
        $this->content_back = $content_back;

        return $this;
    }


    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getColorBack(): ?string
    {
        return $this->color_back;
    }

    public function setColorBack(?string $color_back): self
    {
        $this->color_back = $color_back;

        return $this;
    }

    public function getTag(): ?string
    {
        return $this->tag;
    }

    public function setTag(string $tag): self
    {
        $this->tag = $tag;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Mon Avesnois" />

    <title>{% block title %}Mon Avesnois{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('style.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/dark.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/font-icons.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/animate.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}" type="text/css" />
    <link rel="stylesheet" href="{{ asset('css/bs-select.css') }}" type="text/css" />

    <link rel="stylesheet" href="{{ asset('css/responsive.css') }}" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {% block stylesheets %}{% endblock %}

</head>

<body class="stretched">

<div id="wrapper" class="clearfix">

    <header id="header" class="dark full-header sticky-header">

        <div id="header-wrap">

            <div class="container">

                <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                <div id="logo">
                    <a href="{{ path('home') }}" class="standard-logo" data-dark-logo="{{ asset('images/logo-dark.png') }}"><img src="{{ asset('images/logo-dark.png') }}" alt="Mon Avesnois Logo"></a>
                    <a href="{{ path('home') }}" class="retina-logo" data-dark-logo=""><img src="{{ asset('images/logo-dark.png') }}" alt="Mon Avesnois Logo"></a>
                </div>

                <nav id="primary-menu">

                    <ul class="one-page-menu">
                        <li><a href="{{ path('home') }}"><div>Accueil</div></a></li>
                        <li><a href="blog.php"><div>Actualités</div></a></li>
                        <li><a href="#"><div>Annonces</div></a></li>
                        <li><a href="price.php"><div>Offres</div></a></li>
                        {% if app.user %}
                            <li class="sub-menu"><a href="" class="sf-with-ul"><div>{{ app.user.username }}</div></a>
                                <ul style="display: none;">
                                    {% if app.user.roles == ["ROLE_PRO"] %}
                                        <li><a href="{{ path('pro_profile', {'id': app.user.id}) }}"><div>Profil</div></a></li>
                                    {% else %}
                                        <li><a href="{{ path('profile', {'id': app.user.id}) }}"><div>Profil</div></a></li>
                                    {% endif %}
                                    <li><a href="{{ path('app_logout') }}"><div>Deconnexion</div></a></li>

                                </ul>
                            </li>

                        {% else %}
                            <li><a href="{{ path('app_login') }}"><div>Connexion</div></a></li>
                            <li><a href="{{ path('app_register') }}"><div>Inscription</div></a></li>
                        {% endif %}
                        <li><a href="profil_pro.php"><div>PP*</div></a></li>

                    </ul>

                    <div id="top-search">
                        <a href="{{ path('search') }}" ><i class="icon-search3"></i><i class="icon-line-cross"></i></a>
                    </div>
                </nav>

            </div>

        </div>

    </header>
    {% for message in app.flashes('success') %}
        <div class="style-msg successmsg">
            <div class="sb-msg"><i class="icon-thumbs-up"></i>{{ message }}</div>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    {% endfor %}
    {% for message in app.flashes('errors') %}
        <div class="style-msg errormsg">
            <div class="sb-msg"><i class="icon-thumbs-down"></i>{{ message }}</div>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    {% endfor %}

    {% for message in app.flashes('warning') %}
        <div class="style-msg alertmsg">
            <div class="sb-msg"><i class="icon-thumbs-down"></i>{{ message }}</div>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
    {% endfor %}

    {% block body %}{% endblock %}

    <footer id="footer" class="dark">

        <div id="copyrights">

            <div class="container clearfix">

                <div class="col_half">
                    Copyrights &copy; 2019<br>
                    <div class="copyright-links"><a href="#">Mentions légales</a> / <a href="#">Politique de confidentialités</a></div>
                </div>

                <div class="col_half col_last tright">
                    <div class="fright clearfix">
                        <a href="#" class="social-icon si-small si-borderless si-facebook">
                            <i class="icon-facebook"></i>
                            <i class="icon-facebook"></i>
                        </a>

                        <a href="#" class="social-icon si-small si-borderless si-twitter">
                            <i class="icon-twitter"></i>
                            <i class="icon-twitter"></i>
                        </a>

                        <a href="#" class="social-icon si-small si-borderless si-linkedin">
                            <i class="icon-linkedin"></i>
                            <i class="icon-linkedin"></i>
                        </a>
                    </div>

                    <div class="clear"></div>

                    <i class="icon-line-mail"></i> contact@monavesnois.fr <span class="middot">&middot;</span> <i class="icon-phone"></i> 0102030405 <span class="middot">&middot;</span>
                </div>

            </div>

        </div>

    </footer>

</div>

<div id="gotoTop" class="icon-angle-up"></div>

<script src="{{ asset('js/jquery.js') }}"></script>
<script src="{{ asset('js/plugins.js') }}"></script>
<script src="{{ asset('js/functions.js') }}"></script>
<script src="{{ asset('js/bs-select.js') }}"></script>

<script>
    $(function() {
        $( "#side-navigation" ).tabs({ show: { effect: "fade", duration: 400 } });
    });
</script>
{% block javascripts %}{% endblock %}

</body>
</html>

templates/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page.name }} Contact | {{ parent()}} {% endblock %}

{% block body %}

    {% include "pagepro/menu.html.twig" %}

    <section class="content">

        <div class="content-wrap">

            <div class="container clearfix">

                    <div class="col-lg-12">

                        <div class="fancy-title title-border">
                            <h3>Contacter {{ page.name }}</h3>
                        </div>


                        {% if app.user %}
                            {% if app.user.id != page.user.id %}

                                <div>
                                    {{ form_start(form, {'attr': {'class': 'mb-0'}}) }}

                                    <div class="row">

                                        <div class="w-100"></div>

                                        <div class="col-md-12 col-lg-12 form-group">
                                            {{ form_label(form.subject) }}
                                            {{ form_widget(form.subject, {'attr': {'class': 'required sm-form-control'}}) }}
                                        </div>

                                        <div class="w-100"></div>

                                        <div class="col-12 form-group">
                                            {{ form_label(form.message) }}
                                            {{ form_widget(form.message, {'attr': {'class': 'required sm-form-control', 'rows': '6','cols': '30'}}) }}
                                        </div>

                                        <div class="col-12 form-group">
                                            <button name="submit" type="submit" id="submit-button" tabindex="5" value="Submit" class="button button-3d m-0">Envoyer le message</button>
                                        </div>
                                    </div>

                                    <input type="hidden" name="prefix" value="template-contactform-">

                                    {{ form_end(form) }}
                                </div>

                            {% else %}


                                <div class="alert alert-info">
                                    <i class="icon-eye"></i> Voyons il n'est pas possible de s'envoyer un propre message !
                                </div>
                            {% endif %}
                        {% else %}

                            <div class="alert alert-warning">
                                <i class="icon-warning-sign"></i> Pour contacter {{ page.name }} vous devez vous
                                <a href="{{ path('app_login') }}">connecter</a>, où vous
                                <a href="{{ path('app_register') }}">inscrire</a> si vous n'avez pas encore de compte.
                            </div>

                        {% endif %}
                    </div>

            </div>

        </div>

    </section>

{% endblock %}

templates/home.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <section id="slider" class="slider-element slider-parallax dark full-screen" style="background: url('images/landing1.jpg') center;">

        <div class="slider-parallax-inner">

            <div class="container clearfix">

                <div class="vertical-middle">

                    <div class="heading-block center nobottomborder">
                        <h1 data-animate="fadeInUp">Vous recherchez un professionnels dans l'Avesnois ?</h1>
                        <span data-animate="fadeInUp" data-delay="300">Lancez votre recherche et découvrez les professionnels de votre secteur</span>
                    </div>

{#                    <form action="#" method="post" class="landing-wide-form clearfix">#}
{#                        <div class="col_four_fifth nobottommargin">#}
{#                            <div class="col_one_third nobottommargin">#}
{#                                <input type="text" class="form-control form-control-lg not-dark" value="" placeholder="Votre recherche*">#}
{#                            </div>#}
{#                            <div class="col_one_third nobottommargin">#}
{#                                <input type="email" class="form-control form-control-lg not-dark" value="" placeholder="Votre ville*">#}
{#                            </div>#}
{#                            <div class="col_one_third col_last nobottommargin">#}
{#                                <input type="password" class="form-control form-control-lg not-dark" value="" placeholder="Secteur d'activité*">#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="col_one_fifth col_last nobottommargin">#}
{#                            <button class="btn btn-lg button-green btn-block nomargin" value="submit" type="submit" style="">Rechercher</button>#}
{#                        </div>#}
{#                    </form>#}
                    {% include 'includes/_search.html.twig' %}
                </div>

            </div>

        </div>

    </section>


    <section>
        <div class="container clearfix">
            <div class="content-wrap">
                <div class="container clearfix">

                    <div class="col_one_fourth nobottommargin">
                        <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
                            <div class="fbox-icon">
                                <a href="#"><i class="i-alt noborder icon-shop"></i></a>
                            </div>
                            <h3>lorem<span class="subtitle">Lorem ipsum dolor sit amet consectetur adipisicing elit.</span></h3>
                        </div>
                    </div>

                    <div class="col_one_fourth nobottommargin">
                        <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
                            <div class="fbox-icon">
                                <a href="#"><i class="i-alt noborder icon-wallet"></i></a>
                            </div>
                            <h3>lorem<span class="subtitle">Lorem ipsum dolor sit amet consectetur adipisicing elit.</span></h3>
                        </div>
                    </div>

                    <div class="col_one_fourth nobottommargin">
                        <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
                            <div class="fbox-icon">
                                <a href="#"><i class="i-alt noborder icon-megaphone"></i></a>
                            </div>
                            <h3>lorem<span class="subtitle">Lorem ipsum dolor sit amet consectetur adipisicing elit.</span></h3>
                        </div>
                    </div>

                    <div class="col_one_fourth nobottommargin col_last">
                        <div class="feature-box fbox-center fbox-light fbox-effect nobottomborder">
                            <div class="fbox-icon">
                                <a href="#"><i class="i-alt noborder icon-fire"></i></a>
                            </div>
                            <h3>lorem<span class="subtitle">Lorem ipsum dolor sit amet consectetur adipisicing elit.</span></h3>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container clearfix">

        <div class="content-wrap">

            <div class="heading-block center">

                <h1>Recherche</h1>

                <span>Vous recherchez une entreprise où un service lié à celle-ci ?</span>

            </div>

            <div class="clearfix"></div>

            {% include 'includes/_search.html.twig' %}

            <div class="fancy-title title-border title-center mt-5">

                {% if choice == 1 %}

                    {% if pages != null %}

                        {% if pages|length > 0 %}

                            <h3>Vos résultats ({{ pages|length }})</h3>

                        {% endif %}

                    {% elseif pages|length == 0 and search != null %}

                        <h3 class="text-center">Aucune entreprise trouvé</h3>

                    {% endif %}

                {% else %}

                    {% if services != null %}

                        {% if services|length > 0 %}

                            <h3>Vos résultats ({{ services|length }})</h3>

                        {% endif %}

                    {% elseif services|length == 0 and search != null %}

                        <h3 class="text-center">Aucun service trouvé</h3>

                    {% endif %}

                {% endif %}

                {% if search == null %}

                    <h3 class="text-center">Vous n'avez pas encore effectué de recherche</h3>

                {% endif %}

            </div>

            {% if choice == 1 %}

                {% if pages != null %}
                    <div class="row grid-container has-init-isotope" data-layout="masonry" style="overflow: visible; position: relative; height: 529px;">
                        {% for page in pages %}
                            {% if city == null %}

                                <div class="col-lg-4 mb-4" style="position: absolute; left: 0%; top: 0px;">
                                    <div class="flip-card ">
                                        {#                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('{{ asset('/images/pagepro/service/'~service.imgService) }}')">#}
                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('https://www.fillmurray.com/640/480/?37806')">

                                            <div class="flip-card-inner">
                                                <div class="card bg-transparent border-0 text-center">
                                                    <div class="card-body">
                                                        <h3 id="title" class="card-title">

                                                            {{ page.name }}

                                                        </h3>
                                                        <p class="card-text font-weight-normal" id="content-front">
                                                            {{ page.description|u.truncate(30) }}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="color-back" class="flip-card-back" style="background: {% for service in services %}
                                            {{ service.colorBack }}
                                        {% endfor %};">
                                            <div class="flip-card-inner">
                                                <p class="mb-2 text-white" id="content-back">
                                                    {{ page.address }} - {{ page.city.postal }} {{ page.city.city }}
                                                </p>
                                                <a href="{{ path('page_pro', {'slug': page.slug }) }}" class="btn btn-outline-light mt-2">Voir la page</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            {% elseif page.city.id == city.id %}
                                <div class="col-lg-4 mb-4" style="position: absolute; left: 0%; top: 0px;">
                                    <div class="flip-card ">
                                        {#                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('{{ asset('/images/pagepro/service/'~service.imgService) }}')">#}
                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('https://www.fillmurray.com/640/480/?37806')">

                                            <div class="flip-card-inner">
                                                <div class="card bg-transparent border-0 text-center">
                                                    <div class="card-body">
                                                        <h3 id="title" class="card-title">

                                                            {{ page.name }}

                                                        </h3>
                                                        <p class="card-text font-weight-normal" id="content-front">
                                                            {{ page.description|u.truncate(30) }}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="color-back" class="flip-card-back" style="background: {% for service in services %}
                                            {{ service.colorBack }}
                                        {% endfor %};">
                                            <div class="flip-card-inner">
                                                <p class="mb-2 text-white" id="content-back">
                                                    {{ page.address }} - {{ page.city.postal }} {{ page.city.city }}
                                                </p>
                                                <a href="{{ path('page_pro', {'slug': page.slug }) }}" class="btn btn-outline-light mt-2">Voir la page</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                Aucun résultat trouvé
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}

            {% else %}

                {% if services != null %}
                    <div class="row grid-container has-init-isotope" data-layout="masonry" style="overflow: visible; position: relative; height: 529px;">

                        {% for service in services %}
                            {% if city == null %}

                                <div class="col-lg-4 mb-4" style="position: absolute; left: 0%; top: 0px;">
                                    <div class="flip-card ">
                                        {#                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('{{ asset('/images/pagepro/service/'~service.imgService) }}')">#}
                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('https://www.fillmurray.com/640/480/?37806')">

                                            <div class="flip-card-inner">
                                                <div class="card bg-transparent border-0 text-center">
                                                    <div class="card-body">
                                                        <h3 id="title" class="card-title">

                                                            {{ service.title }}
                                                        </h3>
                                                        <p class="card-text font-weight-normal" id="content-front">
                                                            {{ service.content|raw|u.truncate(80) }}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="color-back" class="flip-card-back" style="background: {% for service in services %}
                                            {{ service.colorBack }}
                                        {% endfor %};">
                                            <div class="flip-card-inner">
                                                <p class="mb-2 text-white" id="content-back">
                                                    {{ service.contentBack }}
                                                </p>
                                                <a href="{{ path('page_pro', {'slug': service.page.slug }) }}" class="btn btn-outline-light mt-2">Voir la page</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            {% elseif service.page.city.id == city.id %}

                                <div class="col-lg-4 mb-4" style="position: absolute; left: 0%; top: 0px;">
                                    <div class="flip-card ">
                                        {#                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('{{ asset('/images/pagepro/service/'~service.imgService) }}')">#}
                                        <div class="flip-card-front dark" id="imgService" style="background-image: url('https://www.fillmurray.com/640/480/?37806')">

                                            <div class="flip-card-inner">
                                                <div class="card bg-transparent border-0 text-center">
                                                    <div class="card-body">
                                                        <h3 id="title" class="card-title">

                                                            {{ service.title }}
                                                        </h3>
                                                        <p class="card-text font-weight-normal" id="content-front">
                                                            {{ service.content|raw|u.truncate(80) }}
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="color-back" class="flip-card-back" style="background: {% for service in services %}
                                            {{ service.colorBack }}
                                        {% endfor %};">
                                            <div class="flip-card-inner">
                                                <p class="mb-2 text-white" id="content-back">
                                                    {{ service.contentBack }}
                                                </p>
                                                <a href="{{ path('page_pro', {'slug': service.page.slug }) }}" class="btn btn-outline-light mt-2">Voir la page</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            {% endif %}
                        {% endfor %}

                    </div>
                {% endif %}

            {% endif %}

        </div>

    </div>

{% endblock %}