src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 * @ORM\Table(name="city", indexes={@ORM\Index(columns={"city"}, flags={"fulltext"})})
 */
class City
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return mixed
     */
    public function __toString()
    {
        return $this->city;
    }

    public function getPostal(): ?string
    {
        return $this->postal;
    }

    public function setPostal(string $postal): self
    {
        $this->postal = $postal;

        return $this;
    }

    /**
     * @return string
     */
    public function getCityPostal(): string
    {
        return $this->city . ' - ' . $this->postal;
    }
}

src/Entity/ContactPro.php
<?php

namespace App\Entity;

use App\Repository\ContactProRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactProRepository::class)
 */
class ContactPro
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $subject;

    /**
     * @ORM\ManyToOne(targetEntity=Page::class, inversedBy="contacts")
     */
    private $page;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $view;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="contactPros")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $view_at;

    public function __construct()
    {
        $this->view = 0;
        $this->created_at = new DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * @param mixed $page
     */
    public function setPage($page): void
    {
        $this->page = $page;
    }

//    public function getPage(): ?Page
//    {
//        return $this->page;
//    }
//
//    public function setPage(?Page $page): self
//    {
//        $this->page = $page;
//
//        return $this;
//    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getView(): ?bool
    {
        return $this->view;
    }

    public function setView(bool $view): self
    {
        $this->view = $view;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }

    public function getViewAt(): ?DateTimeInterface
    {
        return $this->view_at;
    }

    public function setViewAt(?DateTimeInterface $view_at): self
    {
        $this->view_at = $view_at;

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 * @UniqueEntity(fields={"siret"}, message="Le numéro de SIRET est déjà utilisé.")
 * @UniqueEntity(fields={"name"}, message="Le nom de l'entreprise est déjà utilisé.")
 * @UniqueEntity(fields={"email1"}, message="L'adresse email est déjà utilisé.")
 * @UniqueEntity(fields={"email2"}, message="L'adresse email est déjà utilisé.")
 * @UniqueEntity(fields={"tel1"}, message="Le numéro de téléphone est déjà utilisé.")
 * @UniqueEntity(fields={"tel2"}, message="Le numéro de téléphone est déjà utilisé.")
 * @ORM\Table(name="page", indexes={@ORM\Index(columns={"name"}, flags={"fulltext"})})
 */
class Page implements Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=90)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=14, nullable=false)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\NafCode")
     * @ORM\JoinColumn(nullable=false)
     */
    private $naf_code;

    /**
     * @ORM\Column(type="string", length=10, nullable=false)
     */
    private $tel1;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $tel2;

    /**
     * @ORM\Column(type="string", length=80, nullable=false)
     */
    private $email1;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $email2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $valide_admin;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="id_user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_activaded;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $address_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $tel1_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $siret_published;

    /**
     * @ORM\Column(type="boolean")
     */
    private $email1_published;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $fax;

    /**
     * @ORM\OneToOne(targetEntity=ImageLogo::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $imageLogo;

    /**
     * @ORM\OneToOne(targetEntity=ImageBan::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $imageBan;

    /**
     * @ORM\OneToOne(targetEntity=Schedule::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $schedule;

    /**
     * @ORM\Column(type="boolean")
     */
    private $schedule_published;

    /**
     * @ORM\OneToOne(targetEntity=Social::class, mappedBy="page", cascade={"persist", "remove"})
     */
    private $social;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="page")
     */
    private $services;

    /**
     * @ORM\OneToMany(targetEntity=ContactPro::class, mappedBy="page")
     */
    private $contacts;
    private $id_user;

    /**
     * Page constructor.
     */
    public function __construct()
    {
        $this->created_at = new DateTime('now');
        $this->valide_admin = 0;
        $this->is_published = 0;
        $this->is_activaded = 0;
        $this->schedule_published = 0;
        $this->services = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIdUser(): ?Page
    {
        return $this->id_user;
    }

    public function setIdUser(City $id_user): self
    {
        $this->id_user = $id_user;

        // set the owning side of the relation if necessary
        if ($id_user->getUser() !== $this) {
            $id_user->setUser($this);
        }

        return $this;
    }

    public function getTel1(): ?string
    {
        return $this->tel1;
    }

    public function setTel1(?string $tel1): self
    {
        $this->tel1 = $tel1;

        return $this;
    }

    public function getTel2(): ?string
    {
        return $this->tel2;
    }

    public function setTel2(?string $tel2): self
    {
        $this->tel2 = $tel2;

        return $this;
    }

    public function getEmail1(): ?string
    {
        return $this->email1;
    }

    public function setEmail1(?string $email1): self
    {
        $this->email1 = $email1;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email2;
    }

    public function setEmail2(?string $email2): self
    {
        $this->email2 = $email2;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getValideAdmin(): ?bool
    {
        return $this->valide_admin;
    }

    public function setValideAdmin(bool $valide_admin): self
    {
        $this->valide_admin = $valide_admin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getNafCode(): ?NafCode
    {
        return $this->naf_code;
    }

    public function setNafCode(?NafCode $naf_code): self
    {
        $this->naf_code = $naf_code;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getIsActivaded(): ?bool
    {
        return $this->is_activaded;
    }

    public function setIsActivaded(bool $is_activaded): self
    {
        $this->is_activaded = $is_activaded;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getAddressPublished(): ?bool
    {
        return $this->address_published;
    }

    public function setAddressPublished(bool $address_published): self
    {
        $this->address_published = $address_published;

        return $this;
    }

    public function getTel1Published(): ?bool
    {
        return $this->tel1_published;
    }

    public function setTel1Published(bool $tel1_published): self
    {
        $this->tel1_published = $tel1_published;

        return $this;
    }

    public function getSiretPublished(): ?bool
    {
        return $this->siret_published;
    }

    public function setSiretPublished(bool $siret_published): self
    {
        $this->siret_published = $siret_published;

        return $this;
    }


    public function getSchedulePublished(): ?bool
    {
        return $this->schedule_published;
    }

    public function setSchedulePublished(bool $schedule_published): self
    {
        $this->schedule_published = $schedule_published;

        return $this;
    }


    public function getEmail1Published(): ?bool
    {
        return $this->email1_published;
    }

    public function setEmail1Published(bool $email1_published): self
    {
        $this->email1_published = $email1_published;

        return $this;
    }

    public function getFax(): ?string
    {
        return $this->fax;
    }

    public function setFax(?string $fax): self
    {
        $this->fax = $fax;

        return $this;
    }

    public function getImageLogo(): ?ImageLogo
    {

templates/pagepro/alert-msg.html.twig
{% for message in app.flashes('success') %}
    <div class="card-alert card green lighten-5">
        <div class="card-content green-text">
            <p>{{ message }}</p>
        </div>
        <button type="button" class="close green-text" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
    </div>
{% endfor %}

{% for message in app.flashes('errors') %}
        <div class="card-alert card green lighten-5">
            <div class="card-content green-text">
                <p>{{ message }}</p>
            </div>
            <button type="button" class="close green-text" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    {% endfor %}

{% for message in app.flashes('warning') %}
        <div class="card-alert card green lighten-5">
            <div class="card-content green-text">
                <p>{{ message }}</p>
            </div>
            <button type="button" class="close green-text" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    {% endfor %}

templates/pagepro/menu.html.twig
<div class="pp-contenair">

    {% if page.imageBan != null %}
        <div class="bg" style="background: url('{{ asset('/images/pagepro/ban/'~page.imageBan.name) }}') center no-repeat;"></div>
    {% else %}
        <div class="bg" style="background: url('{{ asset('/images/pagepro/ban/default.jpg') }}') center no-repeat;"></div>
    {% endif %}

    <div class="container pp-head clearfix">

        {% if page.imageLogo == null %}
            <img class="aligncenter img-circle img-thumbnail notopmargin nobottommargin"     alt="Logo / {{ page.name }}" style="max-width: 150px;" src="{{ asset('images/pagepro/logo/default.png') }}" >
        {% else %}
            <img class="aligncenter img-circle img-thumbnail notopmargin nobottommargin" alt="Logo / {{ page.name }}" style="max-width: 150px;" src="{{ asset('/images/pagepro/logo/'~page.imageLogo.name) }}" >
        {% endif %}

        <div class="center pp-header">
            <h1>{{ page.name }} </h1>
        </div>


    </div>

</div>

<div id="page-menu" class="no-sticky">
    <div id="page-menu-wrap">
        <div class="container clearfix">
            <div class="menu-title">
                <a href=""><i data-toggle="tooltip" data-placement="top" title="Mettre en favoris" class="i-bookmark icon-bookmark21"></i></a>
                <a href="profil_pro.php" data-toggle="tooltip" data-placement="top" title="{{ page.name }}" class="pp-menu">Accueil</a>
                <a href="" data-toggle="modal" data-target="#horaires" class="pp-menu">Horaires</a>
                <a href="faq.php" class="pp-menu">FAQ</a>
            </div>
            <nav>
                <ul>
                    <li>
                        <a href="#">Magasin en ligne</a>
                    </li>
                    <li>
                        <a href="">Lorem</a>
                    </li>
                    <li>
                        <a href="#">Offre d'emploi </a>
                    </li>
                    <li>
                        <a href="{{ path('contact_page', { 'slug':page.slug } ) }}">Contact</a>
                    </li>

                </ul>
            </nav>
            <div id="page-submenu-trigger"><i class="icon-reorder"></i></div>

        </div>

    </div>
</div>

templates/pagepro/profile_pro_page.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aperçu Ma boutique | {{ parent()}} {% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
{% endblock %}
{% block body %}

    <a href="{{ path('pro_profile', {'id': app.user.id}) }}" class="button button-3d button-rounded button-green">
        <i class="icon-line-arrow-left"></i>
        Retour profil
    </a>
    <div class="style-msg" style="background-color: #EEE;">
        <div class="sb-msg">
            <i class="icon-question-sign"></i>
            Votre page n'est pas encore validé par Mon Avesnois.
            <a href="">En savoir plus</a>
        </div>
    </div>

    {% include "pagepro/menu.html.twig" %}

    <section class="content">

        <div class="content-wrap">

            <div class="container clearfix">

                <div class="postcontent nobottommargin">

                    <h3>Qui sommes nous ?</h3>

                    {{ page.description|raw }}

                </div>

                <div class="sidebar col_last nobottommargin">
                    <h4>Informations</h4>

                    <address>
                        <abbr title="Adresse de la société"><strong>Adresse :</strong></abbr><br>
                        {% if page.addressPublished == 1 %}
                            {{ page.address }} {{ page.city.city }} {{ page.city.postal }}<br>
                        {% else %}
                            Adresse masqué - {{ page.city.city }} - {{ page.city.postal }}
                        {% endif %}
                    </address>

                    <abbr title="Numéro de téléphone"><strong>Tél:</strong></abbr>
                    {% if page.tel1Published == 1  %}
                        {{ page.tel1 }}
                    {% else %}
                        <i>Masqué</i>
                    {% endif %}
                    <br>

                    {% if page.tel2 != null %}
                        <abbr title="Numéro de téléphone 2"><strong>Tel2:</strong></abbr> {{ page.tel2 }}<br>
                    {% endif %}

                    {% if page.fax != null %}
                        <abbr title="Numéro de fax"><strong>Fax:</strong></abbr> {{ page.fax }}<br>
                    {% endif %}

                    <abbr title="Adresse email"><strong>Email:</strong></abbr>
                    {% if page.email1Published == 1 %}
                        {{ page.email1 }}
                    {% else %}
                        <i>Masqué</i>
                    {% endif %}
                    <br>

                    {% if page.email2 != null %}
                        <abbr title="Adresse email"><strong>Email 2:</strong></abbr> {{ page.email2 }}<br>
                    {% endif %}

                    <abbr title="Siret"><strong>SIRET:</strong></abbr>
                    {% if page.siretPublished == 1 %}
                        {{ page.siret }}
                    {% else %}
                        <i>Masqué</i>
                    {% endif %}
                    <br>

                    <abbr title="Code APE"><strong>Code APE:</strong></abbr>
                    {{ page.nafCode.nafCode }}
                    <br>

                    {% if page.website != null %}
                        <abbr title="Site Web"><strong>Site web:</strong></abbr>
                        <a href="{{ page.website }}" target="_blank">Voir le site</a>
                    {% endif %}

                    <div class="social noborder notoppadding">
                        <h4>Réseaux sociaux</h4>

                        {% if page.social.facebook != null %}
                            <a href="https://www.facebook.com/{{ page.social.facebook }}" target="_blank" class="social-icon si-colored si-facebook" data-toggle="tooltip" data-placement="top" title="Facebook">
                                <i class="icon-facebook"></i>
                                <i class="icon-facebook"></i>
                            </a>
                        {% endif %}

                        {% if page.social.twitter != null %}
                            <a href="https://www.twitter.com/{{ page.social.twitter }}" target="_blank" class="social-icon si-colored si-twitter"  data-toggle="tooltip" data-placement="top" title="Twitter">
                                <i class="icon-twitter"></i>
                                <i class="icon-twitter"></i>
                            </a>
                        {% endif %}

                        {% if page.social.tumblr != null %}
                            <a href="https://{{ page.social.tumblr }}/tumblr.com/" target="_blank" class="social-icon si-colored si-tumblr"  data-toggle="tooltip" data-placement="top" title="Tumblr">
                                <i class="icon-tumblr"></i>
                                <i class="icon-tumblr"></i>
                            </a>
                        {% endif %}

                        {% if page.social.youtube != null %}
                            <a href="https://www.youtube.com/user/{{ page.social.youtube }}" target="_blank" class="social-icon si-colored si-youtube"  data-toggle="tooltip" data-placement="top" title="Youtube">
                                <i class="icon-youtube"></i>
                                <i class="icon-youtube"></i>
                            </a>
                        {% endif %}

                        {% if page.social.instagram != null %}
                            <a href="https://www.instagram.com/{{ page.social.instagram }}" target="_blank" class="social-icon si-colored si-instagram"  data-toggle="tooltip" data-placement="top" title="Instagram">
                                <i class="icon-instagram"></i>
                                <i class="icon-instagram"></i>
                            </a>
                        {% endif %}

                        {% if page.social.viadeo != null %}
                            <a href="https://fr.viadeo.com/fr/profile/{{ page.social.viadeo }}" target="_blank" class="social-icon si-colored si-viadeo"  data-toggle="tooltip" data-placement="top" title="Viadeo">
                                <i class="icon-viadeo"></i>
                                <i class="icon-viadeo"></i>
                            </a>
                        {% endif %}

                        {% if page.social.github != null %}
                            <a href="https://github.com/{{ page.social.github }}" target="_blank" class="social-icon si-colored si-github"  data-toggle="tooltip" data-placement="top" title="Github">
                                <i class="icon-github"></i>
                                <i class="icon-github"></i>
                            </a>
                        {% endif %}

                        {% if page.social.flickr != null %}
                            <a href="https://www.flickr.com/photos/{{ page.social.flickr }}" target="_blank" class="social-icon si-colored si-flickr"  data-toggle="tooltip" data-placement="top" title="Flickr">
                                <i class="icon-flickr"></i>
                                <i class="icon-flickr"></i>
                            </a>
                        {% endif %}

                        {% if page.social.pinterest != null %}
                            <a href="https://www.pinterest.fr/{{ page.social.pinterest }}" target="_blank" class="social-icon si-colored si-pinterest"  data-toggle="tooltip" data-placement="top" title="Pinterest">
                                <i class="icon-pinterest"></i>
                                <i class="icon-pinterest"></i>
                            </a>
                        {% endif %}

                        {% if page.social.twitch != null %}
                            <a href="https://www.twitch.tv/{{ page.social.twitch }}" target="_blank" class="social-icon si-colored si-twitch"  data-toggle="tooltip" data-placement="top" title="Twitch">
                                <i class="icon-twitch"></i>
                                <i class="icon-twitch"></i>
                            </a>
                        {% endif %}

                        {% if page.social.linkedin != null %}
                            <a href="https://www.linkedin.com/in/{{ page.social.twitch }}" target="_blank" class="social-icon si-colored si-linkedin"  data-toggle="tooltip" data-placement="top" title="LinkedIn">
                                <i class="icon-linkedin"></i>
                                <i class="icon-linkedin"></i>
                            </a>
                        {% endif %}

                    </div>
                </div>

            </div>
        </div>

    </section>

    <section class="content">

        <div class="container clairfix">

            <div class="fancy-title title-dotted-border title-center">
                <h3 id="services">Nos services / produits</h3>
            </div>


            {% if countService == 5 %}
                {% include 'pagepro/service.html.twig' %}
            {% else %}

                <a href="{{ path('add_service_page_pro') }}" class="btn btn-success">Ajouter un service</a>

            {% endif %}

        </div>

    </section>

    <section class="content">

        <div class="content-wrap">

            <div class="fancy-title title-dotted-border title-center">
                <h3>Où sommes nous ?</h3>
            </div>

            <div id="map"></div>
        </div>

    </section>


    {% include 'pagepro/modal.html.twig' %}

{% endblock %}

{% block javascripts %}

    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
    <script type='text/javascript' src='https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js'></script>

    {% if page.addressPublished == 1 %}
        <script>

            var address = "{{ page.address }} {{ page.city.city }}";

            if(address !== ""){

                $.ajax({
                    url: "https://nominatim.openstreetmap.org/search",
                    type: 'get', // Requête de type GET
                    data: "q="+address+"&format=json&addressdetails=1&limit=1&polygon_svg=1"
                }).done(function (response) {
                    if(response !== ""){

                        if (response.length === 0) {
                            userlat = 50.2784;
                            userlon = 3.9626;
                            var info = "<b>Erreur dans l'adresse :(</b>";
                        }else {
                            userlat = response[0]['lat'];
                            userlon = response[0]['lon'];

                            var info = '<b>{{ page.name|json_encode() }}</b>';

                        }

                        var mymap = L.map('map').setView([userlat, userlon], 13);

                        L.tileLayer('//{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                            maxZoom: 18,
                            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ',
                            tileSize: 512,
                            zoomOffset: -1
                        }).addTo(mymap);
                        //
                        L.marker([userlat, userlon]).addTo(mymap)
                            .bindPopup(info).openPopup();

                    }
                }).fail(function (error) {
                    alert(error);
                });
            }

        </script>
    {% else %}
        <script>

            var address = "{{ page.city.city }} {{ page.city.cityPostal }}";

            if(address !== ""){

                $.ajax({
                    url: "https://nominatim.openstreetmap.org/search",
                    type: 'get', // Requête de type GET
                    data: "q="+address+"&format=json&addressdetails=1&limit=1&polygon_svg=1"
                }).done(function (response) {
                    if(response !== ""){

                        if (response.length === 0) {
                            userlat = 50.2784;
                            userlon = 3.9626;
                            var info = "<b>Erreur dans l'adresse :(</b>";
                        }else {
                            userlat = response[0]['lat'];
                            userlon = response[0]['lon'];
                            var info = "<b>{{ page.name|json_encode() }}</b>";
                        }

                        var mymap = L.map('map').setView([userlat, userlon], 13);

                        L.tileLayer('//{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
                            maxZoom: 18,
                            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ',
                            tileSize: 512,
                            zoomOffset: -1
                        }).addTo(mymap);

                        L.marker([userlat, userlon]).addTo(mymap)
                            .bindPopup(info).openPopup();
                    }
                }).fail(function (error) {
                    alert(error);
                });
            }

        </script>
    {% endif %}

{% endblock %}